spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: dev@5156!@#
      url: jdbc:mysql://81.70.57.148:3306/demo
      filters: stat,wall
      initialSize: 10
      maxActive: 20
      maxOpenPreparedStatements: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 1
      poolPreparedStatements: true
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validation-query-timeout: 500
      validationQuery: SELECT 1
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: true
        url-pattern: /druid/*
